---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dokploy-fleet-ghcr
  namespace: role-playingvideogame
spec:
  encryptedData:
    .dockerconfigjson: AgCs7oagQWNle4k7/+bu8SDfdmrVsuO6RXkZQTvDG17fts17rl2mUzbuReLgQDJJIru8cbPYjWx4EDobF9P5GpbjECjvUdts5dw+9IScJbny5ld/Rl82OL7gVppRv67x5PBMwTmb+1Lm3kufPuoS2OhxpS0thpBpMXC9rdQ2dMoTO3NZ2LfvL+QXiWRn0IV9V2lP2jp2ppHnYWmT51qXQaGEpoWMzYo03jUCoiKMnrQmP2ne+XERApcMgpvEL8fGDdmKRD+K/xvLmHpZprcLhOxx1E2PPmc9usHpqCMvAk6eCW4oTOV+q7hY/1KY5ZiOG8610OPTp5pIgQ0t0wqzVWREqhWGrWv69LlHYvsnSw8LexMjCwd9y5xNChItcWVlbzmAFH3o1SqQuQG0hTicsCENpb7MIojyAFgANLNk1EjzBN8jgpo+VEd4iI0Cq63SJKm1lM14VgGF5cOF3iu0YC9u9lc0tbyKHdF4CLpspsGR22mYdDFB1e7c6g3N7QkvNOu9Gd/bT41nz/umDAyVFXyh3UY/SYb23DwYQYIKSAkoUV1O2B4u7mmK4vlPCxB1A5WYm987386k1fEoK9nyY6vatrjvB3mPuS4AZ7LxVJ8ZnoWZX9ZRuDY4TGmGAEbN5QaIyKcvpjl53g6DDUoX8QIU0DB0sHx7b5T+LjZHFcMSvHWXpyq6TcviABMAmVqFa4urjs2tHR3E0cnQD/9BOm3vCcklRAL/VnRvI2Zs/20l2o91CWlfVII1o1qHnL6Ra1ANXmNc15yDdWlzyIp2rW3zL4OO3F27Snc8lcb/OK3QKtYbbcgOV90dUjd8vDmad1obuojL5lLHIKhQo0dFc9nupeNv2q1CqCgffrl0AORPYaeqydamidJekqp+5zPLYVq9shNjCQ20Unb/OuXnurKNI6AkSLW9fZVkUeDGGBS8Ls3ObvQWj53k+qTstby2FYcUBsqgnlPLJFhhbCM5h9nn
  template:
    metadata:
      name: dokploy-fleet-ghcr
      namespace: role-playingvideogame
    type: kubernetes.io/dockerconfigjson
