apiVersion: v1
kind: Service
metadata:
  name: role-playingvideogame
  labels:
    app.kubernetes.io/name: role-playingvideogame
    app.kubernetes.io/part-of: role-playingvideogame
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: role-playingvideogame
    app.kubernetes.io/part-of: role-playingvideogame
  ports:
    - name: http
      port: 80
      targetPort: 3000
