apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-dns-prod
  namespace: role-playingvideogame
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  acme:
    email: gateszhang92@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-prod-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
