apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/role-playingvideogame
    newTag: fdb06037ee4cfdc3260fae8280ccfd8220fa4446
